language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

before_script:
  - composer self-update
  - composer update

script:
  - mkdir -p build/logs/coverage
  - php vendor/bin/phpunit -c phpunit.xml.dist

after_script:
- wget https://scrutinizer-ci.com/ocular.phar
- php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
